### ISSUE TITLE
EntityFrameworkのバージョン6.3はMigrationが使えません

### ISSUE THREAD

**Issue by kantoexp** [MicrosoftDocs/Contribute.ja-JP#10]
Migration does not work with version 6.3 of EntityFramework. Please improve it as soon as possible.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 70fbb1c8-1435-e762-8824-78cf96faed84
* Version Independent ID: 062879b5-72cf-2353-63f2-d862fe1b40ba
* Content: [Microsoft Docs 共同作成者ガイド概要 - Contributor Guide](https://docs.microsoft.com/ja-jp/contribute/#feedback)
* Content Source: [Contribute/index.md](https://github.com/MicrosoftDocs/Contribute.ja-JP/blob/live/Contribute/index.md)
* Product: **non-product-specific**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @kantoexp
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kantoexp 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/Contribute/issues/330

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
