### ISSUE TITLE
Do not need to translate "Pull Request" to "プル要求" 

### ISSUE THREAD

**Issue by ToruMakabe** [MicrosoftDocs/Contribute.ja-JP#2]
There are several translated word "プル要求" in this repo. But it would be unnecessary because the word having mass appeal.

For instance, the following is a translated doc on GitHub Official site in Japanese.
https://github.co.jp/features

It is appreciated that if you would consider it, thanks.

**Comment by CeciAc** [comment]
Hello @ToruMakabe ,
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello @ToruMakabe 

As this is a global issue we are still reviewing it. We will let you know as soon as we have an update.

Regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello @ToruMakabe 

Sorry for the delay, but our team reviewing this issue. 

Regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello @ToruMakabe

Once again, sorry for the delay, but our team is still reviewing this issue as this is a global change, 

Regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @ToruMakabe ,

 Thank you for your linguistic feedback. 
 
Unfortunately, after reviewing your feedback our linguistic team considered it to be not fully aligned with our criteria for acceptance because the term “pull request” in this context seems to refer to a generic description of the feature. As such, we would not recommend to change it into English in this particular case for the following reason:
For the Japanese language, a generic term which is left in English conventionally takes a headline-style capitalization.  
Therefore, in this case, プル要求 will be changed to Pull Request, which seems to be confusing especially when the UI elements on GitHub appear together with the generic term “pull request” in the same sentence.
Example:
Source: 
2. Create a pull request for the branch in VSTS. You can do this in the Code view on the web from either the Pull Requests tab or the Files tab.

Target when the term “pull request” is reverted to English. 
2. VSTS のブランチに対するPull Request を作成します。これは、Web の [Code] (コード) ビューにある [Pull Requests] (Pull Request) タブ または [Files] (ファイル) タブから行うことができます。

We assume that the concern has been raised because of the possibility of overlocalization of the git commands and UI elements. We confirm that the GitHub commands and UI elements remain in EN in Japanese, since they are part of the code and are not localizable.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team
